keywords_by_lang = {
    "en": [
        "Euro Truck Simulator 2 gameplay", "Farming Simulator 22", "The Sims 4 let's play",
        "Flight Simulator live", "Train Sim World gameplay", "PowerWash Simulator walkthrough",
        "Car Mechanic Simulator stream", "PC Building Simulator tutorial",
        "Bus Simulator multiplayer", "Goat Simulator funny moments",
        "SnowRunner mod showcase", "Surgeon Simulator let's play",
        "Microsoft Flight Simulator 2024 live", "American Truck Simulator gameplay",
        "Farming Simulator 19 mods", "City Car Driving realistic gameplay",
        "Train Simulator 2025 routes", "PowerWash Simulator speedrun",
        "PC Building Simulator 2 build guide", "Bus Simulator 21 career mode",
        "Goat Simulator 3 chaos moments", "SnowRunner co-op missions",
        "Surgeon Simulator VR funny fails", "Flight Simulator cockpit tour",
        "Ship Simulator extreme weather", "Construction Simulator 2022 missions",
        "Lawn Mowing Simulator relaxing gameplay", "Thief Simulator stealth walkthrough",
        "Airport Simulator baggage handling", "Gas Station Simulator expansion",
        "Fishing Simulator big catch", "Police Simulator patrol duty",
        "Cooking Simulator kitchen chaos", "House Flipper renovation tips",
        "Train Sim World 4 realistic routes", "Airport Ground Handling Simulator",
        "Bridge Constructor challenge", "Demolition Simulator building destruction",
        "Flight Simulator landing challenge", "Euro Truck Simulator 2 map expansion",
        "Farming Simulator realistic harvest", "Car Mechanic Simulator barn find",
        "Goat Simulator ragdoll physics", "SnowRunner hardcore mode",
        "Train Simulator scenic routes", "Bus Simulator passenger experience",
        "City Bus Simulator traffic jams", "PC Building Simulator overclocking",
        "Ship Simulator port docking", "PowerWash Simulator satisfying clean",
        "American Truck Simulator convoy", "Flight Simulator storm landing",
        "Construction Simulator heavy machinery", "Airport Simulator boarding process",
        "Thief Simulator night heist", "Lawn Mowing Simulator perfect stripes",
        "Police Simulator high speed chase", "Cooking Simulator gourmet dishes",
        "House Flipper luxury renovation", "Bridge Constructor physics test",
        "Demolition Simulator explosive job", "Fishing Simulator river trip",
        "Gas Station Simulator customer rush", "Surgeon Simulator speed surgery",
        "Goat Simulator world exploration", "SnowRunner extreme terrain",
        "Train Sim World freight hauling", "Bus Simulator route planning",
        "Euro Truck Simulator realistic driving", "Farming Simulator co-op gameplay",
        "Flight Simulator full flight", "Car Mechanic Simulator full rebuild",
        "PC Building Simulator troubleshooting", "PowerWash Simulator rust removal",
        "City Car Driving winter roads", "Ship Simulator rescue mission",
        "Construction Simulator crane operation", "Airport Simulator runway control",
        "Lawn Mowing Simulator garden design", "Thief Simulator stealth tips",
        "Fishing Simulator rare catch", "Police Simulator emergency call",
        "Cooking Simulator speed cooking", "House Flipper tiny house makeover",
        "Bridge Constructor puzzle solution", "Demolition Simulator factory teardown",
        "Gas Station Simulator night shift", "Surgeon Simulator co-op mode",
        "Goat Simulator easter eggs", "SnowRunner trailer hauling",
        "Train Simulator express service", "Bus Simulator scenic route",
        "American Truck Simulator mountain roads", "Flight Simulator VR experience",
        "Farming Simulator crop rotation", "Car Mechanic Simulator tuning",
        "PC Building Simulator RGB build", "PowerWash Simulator graffiti removal",
        "City Car Driving traffic rules", "Ship Simulator iceberg encounter",
        "Construction Simulator teamwork", "Airport Simulator delayed flights",
        "Lawn Mowing Simulator park maintenance", "Thief Simulator loot showcase"
    ],
    "ru": [
        "Евро Трек Симулятор геймплей", "Фарминг Симулятор 22", "Симс 4 летсплей",
        "Флайт Симулятор стрим", "Симулятор автомеханика прохождение",
        "Симулятор сборки ПК обзор", "Сноураннер моды", "Симулятор поезда геймплей",
        "Симулятор охоты стрим", "Симулятор мойки летсплей",
        "Майкрософт Флайт Симулятор 2024 стрим", "Американ Трек Симулятор геймплей",
        "Фарминг Симулятор 19 моды", "Сити Кар Драйвинг реалистичный геймплей",
        "Трейн Симулятор маршруты", "Симулятор мойки спидран",
        "Симулятор сборки ПК 2 гайд", "Бас Симулятор карьера",
        "Гоут Симулятор смешные моменты", "Сноураннер кооп прохождение",
        "Симулятор хирурга VR фейлы", "Флайт Симулятор обзор кабины",
        "Симулятор корабля шторм", "Симулятор строительства миссии",
        "Симулятор газонокосилки расслабляющий геймплей", "Симулятор вора стелс прохождение",
        "Симулятор аэропорта багаж", "Симулятор заправки обновление",
        "Симулятор рыбалки большой улов", "Симулятор полиции патруль",
        "Симулятор готовки хаос на кухне", "Хаус Флиппер ремонт дома",
        "Трейн Сим Ворлд 4 реалистичные маршруты", "Симулятор мостостроителя челлендж",
        "Симулятор сноса зданий разрушение", "Флайт Симулятор посадка в бурю",
        "Евро Трек Симулятор карта DLC", "Фарминг Симулятор уборка урожая",
        "Симулятор автомеханика barn find", "Сноураннер хардкор режим",
        "Бас Симулятор опыт пассажира", "Симулятор корабля швартовка",
        "Симулятор мойки чистка ржавчины", "Американ Трек Симулятор конвой",
        "Симулятор строительства тяжелая техника", "Симулятор аэропорта посадка",
        "Симулятор вора ночное ограбление", "Симулятор газонокосилки идеальные полосы",
        "Симулятор полиции погоня", "Симулятор готовки блюда",
        "Хаус Флиппер ремонт квартиры", "Симулятор мостостроителя тест физики",
        "Симулятор сноса зданий взрыв", "Симулятор рыбалки река",
        "Симулятор заправки ночная смена", "Симулятор хирурга спидран",
        "Гоут Симулятор исследование карты", "Сноураннер экстремальное бездорожье",
        "Трейн Сим Ворлд грузовые перевозки", "Бас Симулятор планирование маршрута",
        "Евро Трек Симулятор реалистичное вождение", "Фарминг Симулятор кооп",
        "Флайт Симулятор полный полет", "Симулятор автомеханика полная сборка",
        "Симулятор сборки ПК настройка", "Симулятор мойки удаление граффити",
        "Сити Кар Драйвинг зимние дороги", "Симулятор корабля спасательная миссия",
        "Симулятор строительства кран", "Симулятор аэропорта управление взлетом",
        "Симулятор газонокосилки дизайн сада", "Симулятор вора советы",
        "Симулятор рыбалки редкая рыба", "Симулятор полиции вызов",
        "Симулятор готовки скорость", "Хаус Флиппер ремонт мини-дома",
        "Симулятор мостостроителя решение", "Симулятор сноса завод",
        "Симулятор заправки час пик", "Симулятор хирурга кооп",
        "Гоут Симулятор пасхалки", "Сноураннер перевозка прицепа",
        "Трейн Симулятор экспресс", "Бас Симулятор живописный маршрут",
        "Американ Трек Симулятор горные дороги", "Флайт Симулятор VR",
        "Фарминг Симулятор севооборот", "Симулятор автомеханика тюнинг",
        "Симулятор сборки ПК с RGB", "Симулятор мойки удаление грязи",
        "Сити Кар Драйвинг правила", "Симулятор корабля айсберг",
        "Симулятор строительства команда", "Симулятор аэропорта задержка рейса",
        "Симулятор газонокосилки уход за парком", "Симулятор вора добыча"
    ],
    "pt": [
        "Simulador de caminhão gameplay", "Farming Simulator 22 Brasil",
        "Simulador de ônibus ao vivo", "Simulador de voo tutorial",
        "Simulador de PC construção", "SnowRunner mods Brasil",
        "Euro Truck Simulator 2 Brasil", "American Truck Simulator gameplay",
        "Farming Simulator 19 mods", "City Car Driving realista",
        "Train Simulator rotas", "PowerWash Simulator limpeza satisfatória",
        "PC Building Simulator dicas", "Bus Simulator carreira",
        "Goat Simulator momentos engraçados", "SnowRunner coop Brasil",
        "Surgeon Simulator VR falhas engraçadas", "Flight Simulator tour de cockpit",
        "Ship Simulator tempestade", "Construction Simulator missões",
        "Lawn Mowing Simulator relaxante", "Thief Simulator furtos noturnos",
        "Airport Simulator bagagens", "Gas Station Simulator atualização",
        "Fishing Simulator grande captura", "Police Simulator patrulha",
        "Cooking Simulator caos na cozinha", "House Flipper reforma",
        "Train Sim World rotas realistas", "Bridge Constructor desafio",
        "Demolition Simulator destruição", "Flight Simulator pouso difícil",
        "Euro Truck Simulator 2 mapa DLC", "Farming Simulator colheita realista",
        "Car Mechanic Simulator restauração", "SnowRunner modo difícil",
        "Bus Simulator experiência de passageiro", "Ship Simulator atracação",
        "PowerWash Simulator remoção de ferrugem", "American Truck Simulator comboio",
        "Construction Simulator máquinas pesadas", "Airport Simulator embarque",
        "Thief Simulator roubo de joias", "Lawn Mowing Simulator faixas perfeitas",
        "Police Simulator perseguição", "Cooking Simulator pratos gourmet",
        "House Flipper reforma de apartamento", "Bridge Constructor física real",
        "Demolition Simulator explosão controlada", "Fishing Simulator pesca no rio",
        "Gas Station Simulator turno da noite", "Surgeon Simulator speedrun",
        "Goat Simulator exploração do mapa", "SnowRunner off-road extremo",
        "Train Sim World transporte de carga", "Bus Simulator planejamento de rota",
        "Euro Truck Simulator direção realista", "Farming Simulator multiplayer",
        "Flight Simulator voo completo", "Car Mechanic Simulator montagem total",
        "PC Building Simulator overclock", "PowerWash Simulator remoção de grafite",
        "City Car Driving estradas de inverno", "Ship Simulator missão de resgate",
        "Construction Simulator operação de guindaste", "Airport Simulator controle de pista",
        "Lawn Mowing Simulator paisagismo", "Thief Simulator dicas de furtos",
        "Fishing Simulator peixe raro", "Police Simulator chamada de emergência",
        "Cooking Simulator cozinha rápida", "House Flipper reforma de mini casa",
        "Bridge Constructor solução de quebra-cabeça", "Demolition Simulator demolição de fábrica",
        "Gas Station Simulator hora do rush", "Surgeon Simulator coop",
        "Goat Simulator easter eggs", "SnowRunner transporte de carga",
        "Train Simulator expresso", "Bus Simulator rota turística",
        "American Truck Simulator estradas de montanha", "Flight Simulator VR",
        "Farming Simulator rotação de culturas", "Car Mechanic Simulator tuning",
        "PC Building Simulator com RGB", "PowerWash Simulator remoção de sujeira",
        "City Car Driving regras de trânsito", "Ship Simulator iceberg",
        "Construction Simulator trabalho em equipe", "Airport Simulator voo atrasado",
        "Lawn Mowing Simulator manutenção de parque", "Thief Simulator saque"
    ],

    "fr": [
        "Simulateur de camion gameplay", "Farming Simulator 22 français",
        "Simulateur de vol en direct", "Simulateur de lavage de voiture let's play",
        "Simulateur de train FR", "Simulateur d'hôpital walkthrough",
        "Euro Truck Simulator 2 France", "American Truck Simulator gameplay",
        "Farming Simulator 19 mods", "City Car Driving réaliste",
        "Train Simulator itinéraires", "PowerWash Simulator nettoyage satisfaisant",
        "PC Building Simulator tutoriel", "Bus Simulator mode carrière",
        "Goat Simulator moments drôles", "SnowRunner coopération FR",
        "Surgeon Simulator VR fails", "Flight Simulator visite du cockpit",
        "Ship Simulator tempête", "Construction Simulator missions",
        "Lawn Mowing Simulator gameplay relaxant", "Thief Simulator cambriolage nocturne",
        "Airport Simulator gestion bagages", "Gas Station Simulator mise à jour",
        "Fishing Simulator grosse prise", "Police Simulator patrouille",
        "Cooking Simulator chaos en cuisine", "House Flipper rénovation",
        "Train Sim World trajets réalistes", "Bridge Constructor défi",
        "Demolition Simulator destruction", "Flight Simulator atterrissage difficile",
        "Euro Truck Simulator 2 DLC carte", "Farming Simulator moisson réaliste",
        "Car Mechanic Simulator restauration", "SnowRunner mode difficile",
        "Bus Simulator expérience passager", "Ship Simulator accostage",
        "PowerWash Simulator suppression rouille", "American Truck Simulator convoi",
        "Construction Simulator engins lourds", "Airport Simulator embarquement",
        "Thief Simulator vol de bijoux", "Lawn Mowing Simulator bandes parfaites",
        "Police Simulator poursuite", "Cooking Simulator plats gastronomiques",
        "House Flipper rénovation appartement", "Bridge Constructor physique réaliste",
        "Demolition Simulator explosion contrôlée", "Fishing Simulator pêche en rivière",
        "Gas Station Simulator service de nuit", "Surgeon Simulator speedrun",
        "Goat Simulator exploration carte", "SnowRunner hors-piste extrême",
        "Train Sim World transport de fret", "Bus Simulator planification itinéraire",
        "Euro Truck Simulator conduite réaliste", "Farming Simulator multijoueur",
        "Flight Simulator vol complet", "Car Mechanic Simulator remontage complet",
        "PC Building Simulator overclocking", "PowerWash Simulator nettoyage graffiti",
        "City Car Driving routes hivernales", "Ship Simulator mission sauvetage",
        "Construction Simulator grue", "Airport Simulator contrôle piste",
        "Lawn Mowing Simulator aménagement paysager", "Thief Simulator astuces",
        "Fishing Simulator poisson rare", "Police Simulator appel d'urgence",
        "Cooking Simulator cuisine rapide", "House Flipper rénovation mini-maison",
        "Bridge Constructor solution puzzle", "Demolition Simulator démolition usine",
        "Gas Station Simulator heure de pointe", "Surgeon Simulator coop",
        "Goat Simulator easter eggs", "SnowRunner transport remorque",
        "Train Simulator express", "Bus Simulator route panoramique",
        "American Truck Simulator routes montagne", "Flight Simulator VR",
        "Farming Simulator rotation cultures", "Car Mechanic Simulator tuning",
        "PC Building Simulator RGB", "PowerWash Simulator enlèvement saleté",
        "City Car Driving code de la route", "Ship Simulator iceberg",
        "Construction Simulator travail en équipe", "Airport Simulator vol retardé",
        "Lawn Mowing Simulator entretien parc", "Thief Simulator butin"
    ],
    "de": [
        "Euro Truck Simulator 2 deutsch", "Flugsimulator live",
        "Landwirtschafts-Simulator 22 Gameplay", "PC-Bausimulator Tutorial",
        "Automechaniker Simulator Deutsch", "Zugsimulator deutsch",
        "SnowRunner deutsch stream",
        "American Truck Simulator deutsch", "Farming Simulator 19 Mods",
        "City Car Driving realistisch", "Train Simulator Strecken",
        "PowerWash Simulator Reinigung", "PC Building Simulator Anleitung",
        "Bus Simulator Karriere", "Goat Simulator lustige Momente",
        "SnowRunner Koop deutsch", "Surgeon Simulator VR Fails",
        "Flugsimulator Cockpit-Tour", "Schiffssimulator Sturm",
        "Bausimulator Missionen", "Rasenmäher Simulator entspannt",
        "Dieb Simulator nächtlicher Raub", "Flughafensimulator Gepäckabfertigung",
        "Tankstellen Simulator Update", "Angelsimulator großer Fang",
        "Polizeisimulator Streifenfahrt", "Kochsimulator Chaos in der Küche",
        "House Flipper Renovierung", "Train Sim World realistische Routen",
        "Brückenbau Simulator Herausforderung", "Abriss-Simulator Zerstörung",
        "Flugsimulator schwierige Landung", "Euro Truck Simulator 2 DLC Karte",
        "Landwirtschafts-Simulator realistische Ernte", "Automechaniker Simulator Restaurierung",
        "SnowRunner Hardcore Modus", "Bus Simulator Passagiererlebnis",
        "Schiffssimulator Anlegen", "PowerWash Simulator Rostentfernung",
        "American Truck Simulator Konvoi", "Bausimulator schwere Maschinen",
        "Flughafensimulator Boarding", "Dieb Simulator Juwelenraub",
        "Rasenmäher Simulator perfekte Linien", "Polizeisimulator Verfolgung",
        "Kochsimulator Gourmetgerichte", "House Flipper Wohnungsrenovierung",
        "Brückenbau Simulator Physik-Test", "Abriss-Simulator Explosion",
        "Angelsimulator Fluss", "Tankstellen Simulator Nachtschicht",
        "Surgeon Simulator Speedrun", "Goat Simulator Karten-Erkundung",
        "SnowRunner extremes Gelände", "Train Sim World Frachttransport",
        "Bus Simulator Routenplanung", "Euro Truck Simulator realistisches Fahren",
        "Landwirtschafts-Simulator Koop", "Flugsimulator kompletter Flug",
        "Automechaniker Simulator Komplettaufbau", "PC Building Simulator Overclocking",
        "PowerWash Simulator Graffiti-Entfernung", "City Car Driving Winterstraßen",
        "Schiffssimulator Rettungsmission", "Bausimulator Kranbedienung",
        "Flughafensimulator Startbahnkontrolle", "Rasenmäher Simulator Gartendesign",
        "Dieb Simulator Tipps", "Angelsimulator seltener Fang",
        "Polizeisimulator Notruf", "Kochsimulator Schnellkochen",
        "House Flipper Minihaus-Renovierung", "Brückenbau Simulator Puzzle-Lösung",
        "Abriss-Simulator Fabrikabriss", "Tankstellen Simulator Stoßzeit",
        "Surgeon Simulator Koop", "Goat Simulator Easter Eggs",
        "SnowRunner Anhängertransport", "Train Simulator Express",
        "Bus Simulator Panoramastrecke", "American Truck Simulator Bergstraßen",
        "Flugsimulator VR", "Landwirtschafts-Simulator Fruchtwechsel",
        "Automechaniker Simulator Tuning", "PC Building Simulator RGB-Build",
        "PowerWash Simulator Schmutzentfernung", "City Car Driving Verkehrsregeln",
        "Schiffssimulator Eisberg", "Bausimulator Teamarbeit",
        "Flughafensimulator Flugverspätung", "Rasenmäher Simulator Parkpflege",
        "Dieb Simulator Beute"
    ],
    "es": [
        "Simulador de camiones gameplay", "Farming Simulator 22 español",
        "Simulador de vuelo en directo", "SnowRunner mods español",
        "Simulador de construcción walkthrough", "Goat Simulator divertido",
        "Euro Truck Simulator 2 España", "American Truck Simulator gameplay",
        "Farming Simulator 19 mods", "City Car Driving realista",
        "Train Simulator rutas", "PowerWash Simulator limpieza satisfactoria",
        "PC Building Simulator tutorial", "Bus Simulator modo carrera",
        "Goat Simulator momentos divertidos", "SnowRunner cooperativo español",
        "Surgeon Simulator VR fallos graciosos", "Flight Simulator tour de cabina",
        "Ship Simulator tormenta", "Construction Simulator misiones",
        "Lawn Mowing Simulator relajante", "Thief Simulator robo nocturno",
        "Airport Simulator manejo de equipaje", "Gas Station Simulator actualización",
        "Fishing Simulator gran captura", "Police Simulator patrulla",
        "Cooking Simulator caos en la cocina", "House Flipper renovación",
        "Train Sim World rutas realistas", "Bridge Constructor desafío",
        "Demolition Simulator demolición", "Flight Simulator aterrizaje difícil",
        "Euro Truck Simulator 2 DLC mapa", "Farming Simulator cosecha realista",
        "Car Mechanic Simulator restauración", "SnowRunner modo difícil",
        "Bus Simulator experiencia pasajero", "Ship Simulator atraque",
        "PowerWash Simulator quitar óxido", "American Truck Simulator convoy",
        "Construction Simulator maquinaria pesada", "Airport Simulator embarque",
        "Thief Simulator robo de joyas", "Lawn Mowing Simulator franjas perfectas",
        "Police Simulator persecución", "Cooking Simulator platos gourmet",
        "House Flipper reforma de apartamento", "Bridge Constructor física real",
        "Demolition Simulator explosión controlada", "Fishing Simulator pesca en río",
        "Gas Station Simulator turno nocturno", "Surgeon Simulator speedrun",
        "Goat Simulator exploración del mapa", "SnowRunner todoterreno extremo",
        "Train Sim World transporte de carga", "Bus Simulator planificación de rutas",
        "Euro Truck Simulator conducción realista", "Farming Simulator multijugador",
        "Flight Simulator vuelo completo", "Car Mechanic Simulator montaje completo",
        "PC Building Simulator overclock", "PowerWash Simulator quitar grafitis",
        "City Car Driving carreteras invernales", "Ship Simulator misión de rescate",
        "Construction Simulator operación de grúa", "Airport Simulator control de pista",
        "Lawn Mowing Simulator diseño de jardín", "Thief Simulator consejos de robo",
        "Fishing Simulator pez raro", "Police Simulator llamada de emergencia",
        "Cooking Simulator cocina rápida", "House Flipper mini casa",
        "Bridge Constructor solución de rompecabezas", "Demolition Simulator demolición de fábrica",
        "Gas Station Simulator hora punta", "Surgeon Simulator cooperativo",
        "Goat Simulator easter eggs", "SnowRunner transporte de remolque",
        "Train Simulator expreso", "Bus Simulator ruta panorámica",
        "American Truck Simulator carreteras de montaña", "Flight Simulator VR",
        "Farming Simulator rotación de cultivos", "Car Mechanic Simulator tuning",
        "PC Building Simulator con RGB", "PowerWash Simulator limpieza de suciedad",
        "City Car Driving normas de tráfico", "Ship Simulator iceberg",
        "Construction Simulator trabajo en equipo", "Airport Simulator vuelo retrasado",
        "Lawn Mowing Simulator mantenimiento de parques", "Thief Simulator botín"
    ],
    "pl": [
        "Symulator ciężarówki gameplay", "Farming Simulator 22 po polsku",
        "Symulator myjki ciśnieniowej", "SnowRunner mody",
        "Symulator pociągu let's play", "Symulator chirurga zabawne",
        "Euro Truck Simulator 2 Polska", "American Truck Simulator gameplay",
        "Farming Simulator 19 mody", "City Car Driving realistyczny",
        "Train Simulator trasy", "PowerWash Simulator satysfakcjonujące czyszczenie",
        "PC Building Simulator poradnik", "Bus Simulator tryb kariery",
        "Goat Simulator śmieszne momenty", "SnowRunner kooperacja PL",
        "Surgeon Simulator VR śmieszne wpadki", "Flight Simulator kokpit tour",
        "Ship Simulator sztorm", "Construction Simulator misje",
        "Lawn Mowing Simulator relaksujący", "Thief Simulator nocny włam",
        "Airport Simulator obsługa bagażu", "Gas Station Simulator aktualizacja",
        "Fishing Simulator wielki połów", "Police Simulator patrol",
        "Cooking Simulator chaos w kuchni", "House Flipper remont",
        "Train Sim World realistyczne trasy", "Bridge Constructor wyzwanie",
        "Demolition Simulator wyburzanie", "Flight Simulator trudne lądowanie",
        "Euro Truck Simulator 2 DLC mapa", "Farming Simulator realistyczne żniwa",
        "Car Mechanic Simulator renowacja", "SnowRunner tryb hardcore",
        "Bus Simulator doświadczenie pasażera", "Ship Simulator cumowanie",
        "PowerWash Simulator usuwanie rdzy", "American Truck Simulator konwój",
        "Construction Simulator ciężki sprzęt", "Airport Simulator boarding",
        "Thief Simulator kradzież biżuterii", "Lawn Mowing Simulator idealne pasy",
        "Police Simulator pościg", "Cooking Simulator dania gourmet",
        "House Flipper remont mieszkania", "Bridge Constructor test fizyki",
        "Demolition Simulator kontrolowane wysadzenie", "Fishing Simulator łowienie w rzece",
        "Gas Station Simulator nocna zmiana", "Surgeon Simulator speedrun",
        "Goat Simulator eksploracja mapy", "SnowRunner ekstremalne bezdroża",
        "Train Sim World przewóz towarów", "Bus Simulator planowanie trasy",
        "Euro Truck Simulator realistyczna jazda", "Farming Simulator multiplayer",
        "Flight Simulator pełny lot", "Car Mechanic Simulator pełna odbudowa",
        "PC Building Simulator overclocking", "PowerWash Simulator usuwanie graffiti",
        "City Car Driving zimowe drogi", "Ship Simulator misja ratunkowa",
        "Construction Simulator obsługa żurawia", "Airport Simulator kontrola pasa",
        "Lawn Mowing Simulator projekt ogrodu", "Thief Simulator porady",
        "Fishing Simulator rzadka ryba", "Police Simulator wezwanie",
        "Cooking Simulator szybkie gotowanie", "House Flipper remont małego domu",
        "Bridge Constructor rozwiązanie zagadki", "Demolition Simulator wyburzanie fabryki",
        "Gas Station Simulator godziny szczytu", "Surgeon Simulator kooperacja",
        "Goat Simulator easter eggs", "SnowRunner transport przyczepy",
        "Train Simulator ekspres", "Bus Simulator trasa widokowa",
        "American Truck Simulator górskie drogi", "Flight Simulator VR",
        "Farming Simulator płodozmian", "Car Mechanic Simulator tuning",
        "PC Building Simulator z RGB", "PowerWash Simulator usuwanie brudu",
        "City Car Driving przepisy ruchu", "Ship Simulator góra lodowa",
        "Construction Simulator praca zespołowa", "Airport Simulator opóźniony lot",
        "Lawn Mowing Simulator utrzymanie parku", "Thief Simulator łup"
    ],
    "uk": [
        "Симулятор вантажівки геймплей", "Farming Simulator українською",
        "Симулятор автобуса огляд", "Симулятор польоту українською",
        "Симулятор мийки геймплей", "SnowRunner український летсплей",
        "Euro Truck Simulator 2 Україна", "American Truck Simulator геймплей",
        "Farming Simulator 19 моди", "City Car Driving реалістичний",
        "Train Simulator маршрути", "PowerWash Simulator задовільне прибирання",
        "PC Building Simulator поради", "Bus Simulator кар’єра",
        "Goat Simulator смішні моменти", "SnowRunner кооп українською",
        "Surgeon Simulator VR фейли", "Flight Simulator тур кабіною",
        "Ship Simulator шторм", "Construction Simulator місії",
        "Lawn Mowing Simulator релакс", "Thief Simulator нічне пограбування",
        "Airport Simulator обслуговування багажу", "Gas Station Simulator оновлення",
        "Fishing Simulator великий улов", "Police Simulator патруль",
        "Cooking Simulator хаос на кухні", "House Flipper ремонт",
        "Train Sim World реалістичні маршрути", "Bridge Constructor виклик",
        "Demolition Simulator знесення", "Flight Simulator складне приземлення",
        "Euro Truck Simulator 2 DLC карта", "Farming Simulator реалістичне жниво",
        "Car Mechanic Simulator реставрація", "SnowRunner хардкор режим",
        "Bus Simulator досвід пасажира", "Ship Simulator швартування",
        "PowerWash Simulator видалення іржі", "American Truck Simulator конвой",
        "Construction Simulator важка техніка", "Airport Simulator посадка",
        "Thief Simulator крадіжка коштовностей", "Lawn Mowing Simulator ідеальні смуги",
        "Police Simulator погоня", "Cooking Simulator страви ресторанного рівня",
        "House Flipper ремонт квартири", "Bridge Constructor тест фізики",
        "Demolition Simulator контрольований вибух", "Fishing Simulator риболовля на річці",
        "Gas Station Simulator нічна зміна", "Surgeon Simulator спідран",
        "Goat Simulator дослідження карти", "SnowRunner екстремальне бездоріжжя",
        "Train Sim World вантажні перевезення", "Bus Simulator планування маршруту",
        "Euro Truck Simulator реалістичне водіння", "Farming Simulator мультиплеєр",
        "Flight Simulator повний політ", "Car Mechanic Simulator повна збірка",
        "PC Building Simulator розгін", "PowerWash Simulator видалення графіті",
        "City Car Driving зимові дороги", "Ship Simulator рятувальна місія",
        "Construction Simulator кран", "Airport Simulator контроль злітної смуги",
        "Lawn Mowing Simulator дизайн саду", "Thief Simulator поради",
        "Fishing Simulator рідкісна риба", "Police Simulator виклик",
        "Cooking Simulator швидке приготування", "House Flipper ремонт маленького будинку",
        "Bridge Constructor розв’язання головоломки", "Demolition Simulator знесення заводу",
        "Gas Station Simulator година пік", "Surgeon Simulator кооп",
        "Goat Simulator пасхалки", "SnowRunner перевезення причепа",
        "Train Simulator експрес", "Bus Simulator мальовничий маршрут",
        "American Truck Simulator гірські дороги", "Flight Simulator VR",
        "Farming Simulator сівозміна", "Car Mechanic Simulator тюнінг",
        "PC Building Simulator з RGB", "PowerWash Simulator прибирання бруду",
        "City Car Driving правила дорожнього руху", "Ship Simulator айсберг",
        "Construction Simulator командна робота", "Airport Simulator затримка рейсу",
        "Lawn Mowing Simulator догляд за парком", "Thief Simulator здобич"
    ],
    "tr": [
        "Kamyon simülatörü oynanış", "Farming Simulator 22 Türkçe",
        "Uçuş simülatörü canlı yayın", "SnowRunner Türkçe modlar",
        "Otobüs simülatörü oynanış", "Goat Simulator Türkçe",
        "Euro Truck Simulator 2 Türkiye", "American Truck Simulator oynanış",
        "Farming Simulator 19 mod tanıtım", "City Car Driving gerçekçi",
        "Train Simulator rotalar", "PowerWash Simulator temizlik",
        "PC Building Simulator rehber", "Bus Simulator kariyer modu",
        "Goat Simulator komik anlar", "SnowRunner Türkçe çok oyunculu",
        "Surgeon Simulator VR hatalar", "Flight Simulator kokpit turu",
        "Ship Simulator fırtına", "Construction Simulator görevler",
        "Lawn Mowing Simulator rahatlatıcı", "Thief Simulator gece soygunu",
        "Airport Simulator bagaj hizmeti", "Gas Station Simulator güncelleme",
        "Fishing Simulator büyük balık avı", "Police Simulator devriye",
        "Cooking Simulator mutfak kaosu", "House Flipper tadilat",
        "Train Sim World gerçekçi tren", "Bridge Constructor köprü yapımı",
        "Demolition Simulator yıkım", "Flight Simulator zorlu iniş",
        "Euro Truck Simulator 2 DLC harita", "Farming Simulator hasat",
        "Car Mechanic Simulator restorasyon", "SnowRunner zorlu arazi",
        "Bus Simulator yolcu deneyimi", "Ship Simulator limana yanaşma",
        "PowerWash Simulator pas temizleme", "American Truck Simulator konvoy",
        "Construction Simulator vinç kullanma", "Airport Simulator pist kontrolü",
        "Thief Simulator mücevher hırsızlığı", "Lawn Mowing Simulator kusursuz çim",
        "Police Simulator kovalamaca", "Cooking Simulator restoran yemekleri",
        "House Flipper apartman yenileme", "Bridge Constructor fizik testi",
        "Demolition Simulator patlama", "Fishing Simulator nehir balıkçılığı",
        "Gas Station Simulator gece vardiyası", "Surgeon Simulator hız denemesi",
        "Goat Simulator harita keşfi", "SnowRunner aşırı offroad",
        "Train Sim World yük taşımacılığı", "Bus Simulator rota planlama",
        "Euro Truck Simulator gerçekçi sürüş", "Farming Simulator çok oyunculu",
        "Flight Simulator tam uçuş", "Car Mechanic Simulator tam montaj",
        "PC Building Simulator overclock", "PowerWash Simulator grafiti temizleme",
        "City Car Driving kış yolları", "Ship Simulator kurtarma görevi",
        "Construction Simulator takım çalışması", "Airport Simulator rötar",
        "Lawn Mowing Simulator park bakımı", "Thief Simulator taktikleri",
        "Fishing Simulator nadir balık", "Police Simulator çağrı",
        "Cooking Simulator hızlı yemek", "House Flipper küçük ev yenileme",
        "Bridge Constructor köprü bulmacası", "Demolition Simulator fabrika yıkımı",
        "Gas Station Simulator yoğun saat", "Surgeon Simulator işbirliği",
        "Goat Simulator gizli yerler", "SnowRunner treyler taşıma",
        "Train Simulator ekspres tren", "Bus Simulator manzaralı rota",
        "American Truck Simulator dağ yolları", "Flight Simulator VR",
        "Farming Simulator ekim biçme", "Car Mechanic Simulator modifiye",
        "PC Building Simulator RGB sistem", "PowerWash Simulator çamur temizleme",
        "City Car Driving trafik kuralları", "Ship Simulator buzdağı",
        "Construction Simulator vinç operasyonu", "Airport Simulator kalkış",
        "Lawn Mowing Simulator bahçe tasarımı", "Thief Simulator soygun planı"
    ],
    "hi": [
        "Truck Simulator Hindi gameplay", "Flight Simulator real time",
        "Farming Simulator 22 walkthrough in Hindi", "Car Mechanic Simulator Hindi",
        "SnowRunner Hindi review", "PC Building Simulator Hindi tutorial",
        "Euro Truck Simulator 2 हिंदी", "American Truck Simulator हिंदी",
        "Farming Simulator 19 हिंदी", "City Car Driving हिंदी",
        "Train Simulator रूट्स", "PowerWash Simulator हिंदी सफाई",
        "Bus Simulator करियर मोड", "Goat Simulator मजेदार पल",
        "Surgeon Simulator हिंदी फनी वीडियो", "Flight Simulator कॉकपिट टूर",
        "Ship Simulator तूफान", "Construction Simulator मिशन",
        "Lawn Mowing Simulator आरामदायक", "Thief Simulator चोरी",
        "Airport Simulator सामान सेवा", "Gas Station Simulator अपडेट",
        "Fishing Simulator बड़ी मछली पकड़ना", "Police Simulator पेट्रोलिंग",
        "Cooking Simulator किचन में मस्ती", "House Flipper मरम्मत",
        "Train Sim World हिंदी", "Bridge Constructor चुनौती",
        "Demolition Simulator विस्फोट", "Flight Simulator कठिन लैंडिंग",
        "Euro Truck Simulator 2 DLC मैप", "Farming Simulator 22 हिंदी फसल",
        "Car Mechanic Simulator मरम्मत", "SnowRunner हिंदी हार्डकोर",
        "Bus Simulator हिंदी अनुभव", "Ship Simulator डॉकिंग",
        "PowerWash Simulator जंग हटाना", "American Truck Simulator काफिला",
        "Construction Simulator भारी मशीनरी", "Airport Simulator बोर्डिंग",
        "Thief Simulator आभूषण चोरी", "Lawn Mowing Simulator सही कटाई",
        "Police Simulator पीछा", "Cooking Simulator तेज़ खाना पकाना",
        "House Flipper छोटा घर मरम्मत", "Bridge Constructor फिजिक्स टेस्ट",
        "Demolition Simulator नियंत्रित विस्फोट", "Fishing Simulator नदी में मछली पकड़ना",
        "Gas Station Simulator नाइट शिफ्ट", "Surgeon Simulator स्पीड रन",
        "Goat Simulator Easter Eggs", "SnowRunner कठिन रास्ते",
        "Train Sim World माल ढुलाई", "Bus Simulator मार्ग योजना",
        "Euro Truck Simulator रियल ड्राइविंग", "Farming Simulator मल्टीप्लेयर",
        "Flight Simulator पूरा उड़ान", "Car Mechanic Simulator फुल रिस्टोरेशन",
        "PC Building Simulator ओवरक्लॉकिंग", "PowerWash Simulator ग्राफ़िटी हटाना",
        "City Car Driving सर्दियों की सड़कें", "Ship Simulator बचाव मिशन",
        "Construction Simulator टीम वर्क", "Airport Simulator उड़ान में देरी",
        "Lawn Mowing Simulator उद्यान डिजाइन", "Thief Simulator टिप्स",
        "Fishing Simulator दुर्लभ मछली", "Police Simulator कॉल रिस्पांस",
        "Cooking Simulator फास्ट कुकिंग", "House Flipper मरम्मत प्रोजेक्ट",
        "Bridge Constructor पहेली हल", "Demolition Simulator फैक्ट्री विस्फोट",
        "Gas Station Simulator पीक आवर्स", "Surgeon Simulator सहयोग",
        "Goat Simulator नक्शा खोज", "SnowRunner ट्रेलर ट्रांसपोर्ट",
        "Train Simulator एक्सप्रेस ट्रेन", "Bus Simulator दृश्य मार्ग",
        "American Truck Simulator पहाड़ी सड़कें", "Flight Simulator VR",
        "Farming Simulator फसल रोटेशन", "Car Mechanic Simulator ट्यूनिंग",
        "PC Building Simulator RGB लाइटिंग", "PowerWash Simulator कीचड़ हटाना",
        "City Car Driving ट्रैफिक नियम", "Ship Simulator आइसबर्ग",
        "Construction Simulator क्रेन ऑपरेशन", "Airport Simulator टेकऑफ",
        "Lawn Mowing Simulator बगीचा रखरखाव", "Thief Simulator चोरी योजना"
    ]

}